# Generated by Django 5.2.16 on 2026-07-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_product_price_nonnegative'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='licensekey',
            constraint=models.UniqueConstraint(fields=('product', 'value'), name='license_key_product_value_unique'),
        ),
    ]
