name: Django Tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Create environment file
        run: cp .env.example .env

      - name: Start Docker services
        run: docker compose up -d --build

      - name: Run lint
        run: docker compose exec -T backend uv run ruff check .
      
      - name: Run tests
        run: docker compose exec -T backend uv run pytest
      